### ISSUE TITLE
Case Insensitive

### ISSUE THREAD

**Issue by Flashy78** [fvbommel/sortorder#2]
Is there a more performant way to use this for case insensitive sorting other than calling .ToLower() on both str1 and str2 before passing them into NaturalLess()?

**Comment by fvbommel** [comment]
There was not, but it seemed like a good addition so there is now.

Check out [the new `casefolded` sub-package](https://github.com/fvbommel/sortorder/tree/main/casefolded)!

According to the included benchmarks it's indeed faster on my machine, probably mostly because it allocates less.

**Comment by Flashy78** [comment]
Quick turnaround, thanks!
